2023-10-15 13:34:40,403 ERROR Infinity polling exception: list index out of range
2023-10-15 13:34:40,404 ERROR Exception traceback:
Traceback (most recent call last):
  File "D:\python\Taskmatic\venv\lib\site-packages\telebot\__init__.py", line 955, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "D:\python\Taskmatic\venv\lib\site-packages\telebot\__init__.py", line 1043, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "D:\python\Taskmatic\venv\lib\site-packages\telebot\__init__.py", line 1118, in __threaded_polling
    raise e
  File "D:\python\Taskmatic\venv\lib\site-packages\telebot\__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "D:\python\Taskmatic\venv\lib\site-packages\telebot\util.py", line 147, in raise_exceptions
    raise self.exception_info
  File "D:\python\Taskmatic\venv\lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
  File "D:\python\Taskmatic\venv\lib\site-packages\telebot\__init__.py", line 6801, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "D:\python\Taskmatic\bot\bot.py", line 275, in yahz
    bot.send_message(message.chat.id,a[data['page']-1]['string'], reply_markup=markup_pages,parse_mode="HTML")
IndexError: list index out of range

2023-10-15 13:35:04,967 ERROR Infinity polling exception: list index out of range
2023-10-15 13:35:04,970 ERROR Exception traceback:
Traceback (most recent call last):
  File "D:\python\Taskmatic\venv\lib\site-packages\telebot\__init__.py", line 955, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "D:\python\Taskmatic\venv\lib\site-packages\telebot\__init__.py", line 1043, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "D:\python\Taskmatic\venv\lib\site-packages\telebot\__init__.py", line 1118, in __threaded_polling
    raise e
  File "D:\python\Taskmatic\venv\lib\site-packages\telebot\__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "D:\python\Taskmatic\venv\lib\site-packages\telebot\util.py", line 147, in raise_exceptions
    raise self.exception_info
  File "D:\python\Taskmatic\venv\lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
  File "D:\python\Taskmatic\venv\lib\site-packages\telebot\__init__.py", line 6801, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "D:\python\Taskmatic\bot\bot.py", line 275, in yahz
    bot.send_message(message.chat.id,a[data['page']-1]['string'], reply_markup=markup_pages,parse_mode="HTML")
IndexError: list index out of range

